# File  : docker-compose.yml
# Author: Matthieu Petiteau <mpetiteau.pro@gmail.com>
# Date  : 04.12.2019

# In our nginx service with pass to our build the args
# DOMAIN and FLASK so we can populate our nginx server
# config automatically. see nginx/Dockerfile

version: "3.2"

services:

  application:
    build: ./core
    # Our Flask app is built to run as a module (`app`). The 
    # app configs are set-up directly in `app/__init__.py`
    command: gunicorn -c gunicorn_ini.py app:app
    env_file:
      - ./.env
    ports:
      - 8000:5000

#   webpack:
#     container_name: webpack
#     build:
#       context: ./core/app/client
#     environment:
#       - RUN_MODE=build
#     volumes:
#       - ./core/app/client:/usr/src/app/
#       - /usr/src/app/node_modules


# volumes:
#   static_volume:
#   media_volume:
      
      

