

version: "3.2"

services:

  application:
    build: ./core
    # Our Flask app is built to run as a module (`app`). The 
    # app configs are set-up directly in `app/__init__.py`
    command: flask run --host=0.0.0.0 --port=5000
    env_file:
      - ./.env
    ports:
      - 5000:5000

#   webpack:
#     container_name: webpack
#     build:
#       context: ./core/app/client
#     environment:
#       - RUN_MODE=build
#     volumes:
#       - ./core/app/client:/usr/src/app/
#       - /usr/src/app/node_modules


# volumes:
#   static_volume:
#   media_volume:
      
      

